### ISSUE TITLE
Example fails to compile on 64-bit Linux with GCC 4.6:  %lld to print int64_t causes error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#10]
```
$ make -C example
...
client.c:33:5: error: format ‘%lld’ expects argument of type ‘long long 
int’, but argument 2 has type ‘uint64_t’ [-Werror=format]
...
$

Cast'ing integer to uintmax_t and using %ju instead fixes this problem.

nanopb 0.1.2

```

Original issue reported on code.google.com by `mikhail....@gmail.com` on 19 May 2012 at 6:11
