### ISSUE TITLE
test_compilation fails to build with protobuf 29.0

### ISSUE THREAD

**Issue by bthmc** [nanopb/nanopb#1097]
With this change:

```diff
diff --git a/MODULE.bazel b/MODULE.bazel
index 8aaa68e..1d5bcef 100644
--- a/MODULE.bazel
+++ b/MODULE.bazel
@@ -10 +10 @@ bazel_dep(name = "rules_proto", version = "6.0.2")
-bazel_dep(name = "protobuf", version = "28.2")
+bazel_dep(name = "protobuf", version = "29.0")
```

The following command:

```
$ bazel build test_compilation
```

Fails with this error:

```
bazel-out/k8-fastbuild/bin/test_compilation_pb/google/protobuf/descriptor.pb.c:9:1: warning: unsigned conversion from 'int' to 'short unsigned int' changes value from '536000000' to '46592' [-Woverflow]
    9 | PB_BIND(google_protobuf_FileDescriptorSet, google_protobuf_FileDescriptorSet, 4)
      | ^~~~~~~
In file included from bazel-out/k8-fastbuild/bin/test_compilation_pb/google/protobuf/descriptor.pb.h:6,
                 from bazel-out/k8-fastbuild/bin/test_compilation_pb/google/protobuf/descriptor.pb.c:4:
bazel-out/k8-fastbuild/bin/test_compilation_pb/google/protobuf/descriptor.pb.c:9:1: error: static assertion failed: "FIELDINFO_DOES_NOT_FIT_width4_field536000000"
    9 | PB_BIND(google_protobuf_FileDescriptorSet, google_protobuf_FileDescriptorSet, 4)
      | ^~~~~~~
bazel-out/k8-fastbuild/bin/test_compilation_pb/google/protobuf/descriptor.pb.c:96:1: warning: unsigned conversion from 'int' to 'short unsigned int' changes value from '536000000' to '46592' [-Woverflow]
   96 | PB_BIND(google_protobuf_SourceCodeInfo, google_protobuf_SourceCodeInfo, 4)
      | ^~~~~~~
bazel-out/k8-fastbuild/bin/test_compilation_pb/google/protobuf/descriptor.pb.c:96:1: error: static assertion failed: "FIELDINFO_DOES_NOT_FIT_width4_field536000000"
   96 | PB_BIND(google_protobuf_SourceCodeInfo, google_protobuf_SourceCodeInfo, 4)
      | ^~~~~~~
```

Is this a static assert in disguise? I do not understand the error, and have no idea how to work it around. Thanks.

**Comment by PetteriAimonen** [comment]
Yeah, those are static asserts failing.

The problem is caused by this change in protobuf descriptor.proto, which introduces an extension with tag number 536000000.
https://github.com/protocolbuffers/protobuf/commit/9d7236b421634afcecc24b6fd63da0ff5b506394

By default nanopb 0.4.x uses 16-bit integers for storing tag numbers, so this doesn't fit.
Adding the C define `PB_FIELD_32BIT` fixes the compilation problem.

@schultetwin @nathaniel-brough Do you have thoughts on how to update the bazel test build.
I see these options:

1. Specify `PB_FIELD_32BIT` for that one compilation test.
2. Specify it for all tests.
3. Have an `.options` file that skips those extension fields.
4. Don't use `descriptor.proto` in the tests.

I think 1. is the most straightforward, but I still need a bit of guidance on how to do that with Bazel :)

**Comment by PetteriAimonen** [comment]
Thanks, this should be fixed now.
