### ISSUE TITLE
Calling protoc through nanopb_generator doesn't work for Python 2

### ISSUE THREAD

**Issue by PetteriAimonen** [nanopb/nanopb#503]
```
petteri@oddish:~/nanopb$ python generator/nanopb_generator.py test.proto
Traceback (most recent call last):
  File "generator/nanopb_generator.py", line 2055, in <module>
    main_cli()
  File "generator/nanopb_generator.py", line 1936, in main_cli
    with tempfile.TemporaryDirectory() as tmpdir:
AttributeError: 'module' object has no attribute 'TemporaryDirectory'
```

Regression caused by #486.
