### ISSUE TITLE
Example fails to compile on 64-bit Linux with GCC 4.6:  cast from pointer to integer of different size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nanopb/nanopb#9]
```
What steps will reproduce the problem?

$ make -C example
...
common.c: In function ‘write_callback’:
common.c:13:14: error: cast from pointer to integer of different size 
[-Werror=pointer-to-int-cast]
...
$

GCC complains about void* <-> int conversion. Converting through intptr_t fixes 
this problem.

nanopb 0.1.2

```

Original issue reported on code.google.com by `mikhail....@gmail.com` on 19 May 2012 at 6:08
